name: uot_transport
description: "An application for booking trips in the University of Tripoli, Libya"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.16.0
  firebase_messaging: ^14.7.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.1
  mobile_scanner: ^6.0.6
  google_maps_flutter: ^2.10.1
  logger: ^2.5.0
  shared_preferences: ^2.5.2
  laravel_echo: ^1.0.0-beta.1
  socket_io_client: ^3.1.2
  another_flushbar: ^1.12.30
  lottie: ^3.3.1
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/heroicons-outline/
    - assets/icons/heroicons-solid/
    - assets/icons/
    - assets/images/Comp 1 (1).json
    - assets/images/splashScreen.json

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
          weight: 800